import type { JobRun, RunDetail } from '@/types/run'
import type { SyncSource } from '@/types/source'

export const mockSources: SyncSource[] = [
  {
    id: 1,
    name: '电影目录任务',
    local_path: '/data/movies',
    remote_path: '/同步上传/电影',
    upload_mode: 'fast_then_multipart',
    suffix_rules: ['.mp4', '.mkv', '.avi'],
    exclude_rules: ['sample', '.part'],
    cron_expr: '0 */6 * * *',
    enabled: true,
    updated_at: '2026-03-30 08:30:00',
    schedule_state: {
      is_scheduled: true,
      last_run_at: '2026-03-30 07:00:00',
      next_run_time: '2026-03-30 12:00:00',
      last_run_status: 'success',
    },
  },
  {
    id: 2,
    name: '纪录片目录任务',
    local_path: '/data/documentary',
    remote_path: '/同步上传/纪录片',
    upload_mode: 'fast_only',
    suffix_rules: ['.mp4', '.ts'],
    exclude_rules: [],
    cron_expr: '0 2 * * *',
    enabled: true,
    updated_at: '2026-03-30 08:28:00',
    schedule_state: {
      is_scheduled: true,
      last_run_at: '2026-03-30 06:00:00',
      next_run_time: '2026-03-31 02:00:00',
      last_run_status: 'partial_failed',
    },
  },
  {
    id: 3,
    name: '资料归档任务',
    local_path: '/data/archive',
    remote_path: '/同步上传/资料',
    upload_mode: 'multipart_only',
    suffix_rules: ['.zip', '.rar', '.7z'],
    exclude_rules: ['temp/*'],
    cron_expr: '',
    enabled: false,
    updated_at: '2026-03-30 08:20:00',
    schedule_state: {
      is_scheduled: false,
      last_run_at: null,
      next_run_time: null,
      last_run_status: null,
    },
  },
]

export const mockRuns: JobRun[] = [
  {
    id: 1001,
    source_id: 1,
    source_name: '电影目录任务',
    trigger_type: 'manual',
    status: 'success',
    started_at: '2026-03-30 07:00:00',
    finished_at: '2026-03-30 07:05:12',
    summary: {
      total_files: 12,
      fast_uploaded: 8,
      multipart_uploaded: 3,
      skipped: 1,
      failed: 0,
    },
    error_message: '',
  },
  {
    id: 1002,
    source_id: 2,
    source_name: '纪录片目录任务',
    trigger_type: 'cron',
    status: 'partial_failed',
    started_at: '2026-03-30 06:00:00',
    finished_at: '2026-03-30 06:10:45',
    summary: {
      total_files: 15,
      fast_uploaded: 5,
      multipart_uploaded: 0,
      skipped: 7,
      failed: 3,
    },
    error_message: '部分文件秒传未命中且当前策略禁止分片上传。',
  },
]

export const mockRunDetails: RunDetail[] = [
  {
    ...mockRuns[0],
    records: [
      {
        id: 1,
        relative_path: '科幻/星际穿越.mkv',
        file_size: 2147483648,
        suffix: '.mkv',
        action: 'fast_uploaded',
        message: '秒传命中',
        synced_at: '2026-03-30 07:01:22',
      },
      {
        id: 2,
        relative_path: '科幻/沙丘.mp4',
        file_size: 1234567890,
        suffix: '.mp4',
        action: 'multipart_uploaded',
        message: '秒传未命中，已回退分片上传',
        synced_at: '2026-03-30 07:03:40',
      },
    ],
    logs: [
      {
        id: 101,
        run_id: 1001,
        source_id: 1,
        level: 'info',
        stage: 'start',
        message: '任务开始执行，准备扫描本地目录。',
        created_at: '2026-03-30 07:00:00',
      },
      {
        id: 102,
        run_id: 1001,
        source_id: 1,
        level: 'info',
        stage: 'scan',
        message: '扫描完成，共发现 12 个候选文件。',
        created_at: '2026-03-30 07:00:21',
      },
      {
        id: 103,
        run_id: 1001,
        source_id: 1,
        level: 'info',
        stage: 'upload',
        message: '秒传 8 个文件，分片上传 3 个文件。',
        created_at: '2026-03-30 07:04:58',
      },
      {
        id: 104,
        run_id: 1001,
        source_id: 1,
        level: 'info',
        stage: 'finish',
        message: '任务执行完成。',
        created_at: '2026-03-30 07:05:12',
      },
    ],
  },
  {
    ...mockRuns[1],
    records: [
      {
        id: 3,
        relative_path: '记录/样片/sample.ts',
        file_size: 34359738,
        suffix: '.ts',
        action: 'skipped',
        message: '命中排除规则 sample',
        synced_at: '2026-03-30 06:02:00',
      },
      {
        id: 4,
        relative_path: '记录/深海世界.ts',
        file_size: 987654321,
        suffix: '.ts',
        action: 'failed',
        message: '秒传未命中，当前策略为仅秒传',
        synced_at: '2026-03-30 06:08:10',
      },
    ],
    logs: [
      {
        id: 201,
        run_id: 1002,
        source_id: 2,
        level: 'info',
        stage: 'start',
        message: '定时任务触发，开始执行。',
        created_at: '2026-03-30 06:00:00',
      },
      {
        id: 202,
        run_id: 1002,
        source_id: 2,
        level: 'info',
        stage: 'filter',
        message: '过滤后剩余 15 个文件，跳过 7 个文件。',
        created_at: '2026-03-30 06:01:35',
      },
      {
        id: 203,
        run_id: 1002,
        source_id: 2,
        level: 'warning',
        stage: 'upload',
        message: '3 个文件未命中秒传，且当前任务禁止分片上传。',
        created_at: '2026-03-30 06:08:10',
      },
      {
        id: 204,
        run_id: 1002,
        source_id: 2,
        level: 'error',
        stage: 'finish',
        message: '任务执行结束，状态为部分失败。',
        created_at: '2026-03-30 06:10:45',
      },
    ],
  },
]
